# Generated by Django 6.0.2 on 2026-03-15 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville', models.CharField(choices=[('Kinshasa', 'Kinshasa'), ('Lubumbashi', 'Lubumbashi'), ('Goma', 'Goma'), ('Kolwezi', 'Kolwezi')], max_length=20)),
                ('commune', models.CharField(max_length=255)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('devise', models.CharField(choices=[('USD', 'USD'), ('CDF', 'CDF')], max_length=3)),
                ('description', models.TextField()),
                ('nb_chambres', models.IntegerField()),
                ('eau_regideso', models.BooleanField(default=False)),
                ('elec_snel', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('cloture', models.BooleanField(default=False)),
                ('video_preuve', models.FileField(upload_to='videos_verification/')),
                ('carte_id_proprio', models.ImageField(upload_to='id_verif/')),
                ('gps_lat', models.FloatField(blank=True, null=True)),
                ('gps_long', models.FloatField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='logements_photos/')),
                ('logement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='annonces.logement')),
            ],
        ),
    ]
