# Generated by Django 6.0.2 on 2026-03-15 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logement',
            name='contact_proprietaire',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='logement',
            name='statut',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Loue', 'Loue'), ('Indisponible', 'Indisponible')], default='Disponible', max_length=20),
        ),
    ]
