# Generated by Django 6.0.2 on 2026-03-15 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0003_logement_sentinelle_contactunlock'),
    ]

    operations = [
        migrations.AddField(
            model_name='logement',
            name='telephone_proprio',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
