# Generated by Django 6.0.2 on 2026-03-15 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0004_logement_telephone_proprio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='logement',
            name='motif_rejet',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logement',
            name='proprietaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logements', to=settings.AUTH_USER_MODEL),
        ),
    ]
