# Generated by Django 6.0.2 on 2026-03-15 22:13

from django.db import migrations, models


def migrate_logement_status(apps, schema_editor):
    Logement = apps.get_model("annonces", "Logement")

    for logement in Logement.objects.all():
        logement.disponibilite = logement.statut

        if logement.is_verified:
            logement.statut = "APPROUVEE"
        elif logement.motif_rejet:
            logement.statut = "REJETEE"
        else:
            logement.statut = "EN_ATTENTE"

        logement.save(update_fields=["disponibilite", "statut"])


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0005_logement_motif_rejet_logement_proprietaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='logement',
            name='disponibilite',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Loue', 'Loue'), ('Indisponible', 'Indisponible')], default='Disponible', max_length=20),
        ),
        migrations.RunPython(migrate_logement_status, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='logement',
            name='is_verified',
        ),
        migrations.AlterField(
            model_name='logement',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_ATTENTE', 'En attente'), ('APPROUVEE', 'Approuvee'), ('REJETEE', 'Rejetee')], default='EN_ATTENTE', max_length=20),
        ),
    ]
