# Generated by Django 6.0.2 on 2026-03-15 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0006_remove_logement_is_verified_logement_disponibilite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logement',
            name='type_transaction',
            field=models.CharField(choices=[('LOCATION', 'Location'), ('VENTE', 'Vente')], default='LOCATION', max_length=20),
        ),
        migrations.AddField(
            model_name='logement',
            name='ville_autre',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='logement',
            name='ville',
            field=models.CharField(choices=[('Kinshasa', 'Kinshasa'), ('Lubumbashi', 'Lubumbashi'), ('Goma', 'Goma'), ('Kolwezi', 'Kolwezi'), ('AUTRE', 'Autre')], max_length=20),
        ),
    ]
