# Generated by Django 6.0.2 on 2026-03-15 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0007_logement_type_transaction_logement_ville_autre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logement',
            name='ville',
            field=models.CharField(choices=[('Kinshasa', 'Kinshasa'), ('Lubumbashi', 'Lubumbashi'), ('Goma', 'Goma'), ('Kolwezi', 'Kolwezi'), ('Kisangani', 'Kisangani'), ('Mbuji-Mayi', 'Mbuji-Mayi'), ('Kananga', 'Kananga'), ('Bukavu', 'Bukavu'), ('Matadi', 'Matadi'), ('Boma', 'Boma'), ('Mbandaka', 'Mbandaka'), ('Kindu', 'Kindu'), ('Bunia', 'Bunia'), ('Uvira', 'Uvira'), ('Kikwit', 'Kikwit'), ('Tshikapa', 'Tshikapa'), ('Likasi', 'Likasi'), ('Kalemie', 'Kalemie'), ('Beni', 'Beni'), ('Butembo', 'Butembo'), ('Isiro', 'Isiro'), ('AUTRE', 'Autre')], max_length=20),
        ),
    ]
