# Generated by Django 6.0.3 on 2026-03-15 22:52

from django.db import migrations, models


def migrate_loue_value(apps, schema_editor):
    Logement = apps.get_model("annonces", "Logement")
    Logement.objects.filter(disponibilite="Loue").update(disponibilite="LOUE")


def revert_loue_value(apps, schema_editor):
    Logement = apps.get_model("annonces", "Logement")
    Logement.objects.filter(disponibilite="LOUE").update(disponibilite="Loue")


class Migration(migrations.Migration):

    dependencies = [
        ("annonces", "0008_alter_logement_ville"),
    ]

    operations = [
        migrations.RunPython(migrate_loue_value, revert_loue_value),
        migrations.AlterField(
            model_name="logement",
            name="disponibilite",
            field=models.CharField(
                choices=[
                    ("Disponible", "Disponible"),
                    ("LOUE", "Lou\u00e9"),
                    ("Indisponible", "Indisponible"),
                ],
                default="Disponible",
                max_length=20,
                verbose_name="Disponibilit\u00e9",
            ),
        ),
        migrations.AlterField(
            model_name="logement",
            name="statut",
            field=models.CharField(
                choices=[
                    ("BROUILLON", "Brouillon"),
                    ("EN_ATTENTE", "En attente"),
                    ("APPROUVEE", "Approuv\u00e9e"),
                    ("REJETEE", "Rejet\u00e9e"),
                    ("LOUE", "Lou\u00e9"),
                    ("VENDU", "Vendu"),
                ],
                default="EN_ATTENTE",
                max_length=20,
            ),
        ),
    ]
