# Generated by Django 6.0.3 on 2026-03-15 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annonces", "0009_alter_logement_disponibilite_alter_logement_statut"),
    ]

    operations = [
        migrations.AddField(
            model_name="logement",
            name="categorie_bien",
            field=models.CharField(
                choices=[
                    ("Appartement", "Appartement"),
                    ("Maison", "Maison"),
                    ("Studio", "Studio"),
                    ("Chambre", "Chambre"),
                    ("Bureau", "Bureau"),
                    ("Terrain", "Terrain"),
                    ("Entrepot", "Entrep\u00f4t"),
                ],
                default="Appartement",
                max_length=30,
            ),
        ),
    ]
