# Generated by Django 6.0.3 on 2026-03-15 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annonces", "0010_logement_categorie_bien"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logement",
            name="disponibilite",
            field=models.CharField(
                choices=[
                    ("Disponible", "Disponible"),
                    ("LOUE", "Lou\u00e9"),
                    ("VENDU", "Vendu"),
                    ("Indisponible", "Indisponible"),
                ],
                default="Disponible",
                max_length=20,
                verbose_name="Disponibilit\u00e9",
            ),
        ),
    ]
