# Generated by Django 6.0.3 on 2026-03-15 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0011_alter_logement_disponibilite'),
    ]

    operations = [
        migrations.AddField(
            model_name='logement',
            name='point_repere',
            field=models.CharField(default='', max_length=255),
        ),
    ]
