# Generated by Django 6.0.3 on 2026-03-16 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_moderators_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.get_or_create(name="Mod\u00e9rateurs")


def remove_moderators_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name="Mod\u00e9rateurs").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("annonces", "0012_logement_point_repere"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="logement",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_logements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(create_moderators_group, remove_moderators_group),
    ]
