# Generated by Django 6.0.3 on 2026-03-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0013_logement_verified_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='logement',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logement',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
