# Generated by Django 6.0.3 on 2026-03-16 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0014_logement_approved_at_logement_rejected_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentaireAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires_admin', to=settings.AUTH_USER_MODEL)),
                ('logement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires_admin', to='annonces.logement')),
            ],
            options={
                'ordering': ['date_creation'],
            },
        ),
    ]
