# Generated by Django 6.0.3 on 2026-03-16 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0015_commentaireadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaireadmin',
            name='read_by_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commentaireadmin',
            name='read_by_staff',
            field=models.BooleanField(default=False),
        ),
    ]
