# Generated by Django 6.0.3 on 2026-03-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0017_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logement',
            name='video_preuve',
            field=models.FileField(blank=True, null=True, upload_to='videos_verification/'),
        ),
    ]
