# Generated by Django 6.0.3 on 2026-03-16 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0018_alter_logement_video_preuve'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(choices=[('ARNAQUE', 'Arnaque'), ('DEJA_LOUE', 'Deja loue'), ('PRIX_INCORRECT', 'Prix incorrect'), ('FAUSSE_INFO', 'Fausse information')], max_length=30)),
                ('commentaire', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('logement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to='annonces.logement')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('logement', 'utilisateur'), name='unique_signalement_par_utilisateur')],
            },
        ),
    ]
