# Generated by Django 6.0.3 on 2026-03-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0020_favori'),
    ]

    operations = [
        migrations.AddField(
            model_name='logement',
            name='nb_salles_bain',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='logement',
            name='surface_m2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
