# Generated by Django 6.0.3 on 2026-03-16 10:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0022_messagevisiteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='logement',
            name='adresse',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='logement',
            name='code_immo',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='logement',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
