# Generated by Django 6.0.3 on 2026-03-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0023_logement_adresse_logement_code_immo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logement',
            name='categorie_bien',
            field=models.CharField(choices=[('Appartement', 'Appartement'), ('Maison', 'Maison'), ('Villa', 'Villa'), ('Studio', 'Studio'), ('Chambre', 'Chambre'), ('Bureau', 'Bureau'), ('Terrain', 'Terrain'), ('Entrepot', 'Entrepôt')], default='Appartement', max_length=30),
        ),
    ]
