# Generated by Django 6.0.3 on 2026-03-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0024_alter_logement_categorie_bien'),
    ]

    operations = [
        migrations.AddField(
            model_name='logement',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
