from django.urls import path

from .forms import StyledPasswordResetForm
from .views import (
    about_view,
    agencies_view,
    compare_view,
    contact_owner_message,
    conversation_view,
    contact_view,
    help_center_view,
    messagerie_view,
    privacy_view,
    pricing_view,
    proprietaire_profile,
    premium_view,
    SitePasswordChangeView,
    SitePasswordResetCompleteView,
    SitePasswordResetConfirmView,
    SitePasswordResetDoneView,
    SitePasswordResetView,
    create_logement,
    edit_logement,
    envoyer_message_moderation,
    home,
    login_view,
    logement_detail,
    logout_view,
    mes_annonces,
    mes_favoris,
    mon_profil,
    notifications_view,
    repondre_commentaire,
    safety_view,
    signaler_annonce,
    signup_view,
    tableau_moderation,
    terms_view,
    toggle_compare,
    toggle_favori,
    update_listing_status,
    unlock_contact,
)


app_name = "annonces"

urlpatterns = [
    path("", home, name="home"),
    path("a-propos/", about_view, name="about"),
    path("agences/", agencies_view, name="agencies"),
    path("comparer/", compare_view, name="compare"),
    path("contact/", contact_view, name="contact"),
    path("aide/", help_center_view, name="help_center"),
    path("messages/", messagerie_view, name="messagerie"),
    path("messages/logements/<int:logement_id>/<int:user_id>/", conversation_view, name="conversation"),
    path("conditions/", terms_view, name="terms"),
    path("confidentialite/", privacy_view, name="privacy"),
    path("eviter-les-arnaques/", safety_view, name="safety"),
    path("offres-premium/", premium_view, name="premium"),
    path("tarifs/", pricing_view, name="pricing"),
    path("publier/", create_logement, name="create_logement"),
    path("profil/", mon_profil, name="mon_profil"),
    path("proprietaires/<int:user_id>/", proprietaire_profile, name="proprietaire_profile"),
    path("mes-annonces/", mes_annonces, name="mes_annonces"),
    path("favoris/", mes_favoris, name="mes_favoris"),
    path("notifications/", notifications_view, name="notifications"),
    path("mes-annonces/<int:logement_id>/repondre/", repondre_commentaire, name="repondre_commentaire"),
    path("logements/<int:id>/modifier/", edit_logement, name="edit_logement"),
    path("logements/<int:id>/statut/<str:target_status>/", update_listing_status, name="update_listing_status"),
    path("signup/", signup_view, name="signup"),
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
    path(
        "mot-de-passe/changer/",
        SitePasswordChangeView.as_view(),
        name="password_change",
    ),
    path(
        "mot-de-passe-oublie/",
        SitePasswordResetView.as_view(),
        name="password_reset",
    ),
    path(
        "mot-de-passe-oublie/envoye/",
        SitePasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reinitialiser/<uidb64>/<token>/",
        SitePasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reinitialiser/termine/",
        SitePasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path("gestion-admin/", tableau_moderation, name="gestion_admin"),
    path("gestion-admin/<int:logement_id>/message/", envoyer_message_moderation, name="envoyer_message_moderation"),
    path("moderation/", tableau_moderation, name="tableau_moderation"),
    path("logements/<int:id>/", logement_detail, name="details"),
    path("logement/<int:pk>/", logement_detail, name="logement_detail"),
    path("logements/<int:logement_id>/unlock-contact/", unlock_contact, name="unlock_contact"),
    path("logements/<int:logement_id>/contacter/", contact_owner_message, name="contact_owner_message"),
    path("logements/<int:logement_id>/signaler/", signaler_annonce, name="signaler_annonce"),
    path("logements/<int:logement_id>/favori/", toggle_favori, name="toggle_favori"),
    path("logements/<int:logement_id>/compare/", toggle_compare, name="toggle_compare"),
]
